### ISSUE TITLE
Having a constraint for an property called "attributes" fails

### ISSUE THREAD

**Issue by mburak** [grails/gorm-neo4j#1] opened 2016-06-14 22:25 UTC
We have one object that has an attribute property and we have a constraint for it, no matter what the constraint is (just nullable:true would do it). We we start up the application we get this exception:

```Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.grails.datastore.gorm.neo4j.Neo4jDatastore]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException: object is not an instance of declaring class
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:163)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:122)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:267)
	... 60 more
Caused by: java.lang.IllegalArgumentException: object is not an instance of declaring class
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1210)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1123)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1127)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1123)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at com.brinqa.platform.core.model.DataModel$__clinit__closure16.doCall(DataModel.groovy:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1210)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1123)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
	at groovy.lang.Closure.call(Closure.java:426)
	at com.brinqa.platform.core.model.DataModel$__clinit__closure16.call(DataModel.groovy)
	at groovy.lang.Closure.call(Closure.java:442)
	at com.brinqa.platform.core.model.DataModel$__clinit__closure16.call(DataModel.groovy)
	at org.grails.datastore.mapping.config.groovy.DefaultMappingConfigurationBuilder.evaluate(DefaultMappingConfigurationBuilder.groovy:88)
	at org.grails.datastore.mapping.config.groovy.DefaultMappingConfigurationBuilder.evaluate(DefaultMappingConfigurationBuilder.groovy)
	at org.grails.datastore.mapping.config.AbstractGormMappingFactory.evaluateWithContext(AbstractGormMappingFactory.java:99)
	at org.grails.datastore.mapping.config.AbstractGormMappingFactory.createMappedForm(AbstractGormMappingFactory.java:84)
	at org.grails.datastore.gorm.neo4j.GraphPersistentEntity.<init>(GraphPersistentEntity.groovy:47)
	at org.grails.datastore.gorm.neo4j.Neo4jMappingContext.createPersistentEntity(Neo4jMappingContext.java:116)
	at org.grails.datastore.gorm.neo4j.Neo4jMappingContext.createPersistentEntity(Neo4jMappingContext.java:111)
	at org.grails.datastore.mapping.model.AbstractMappingContext.addPersistentEntities(AbstractMappingContext.java:199)
	at org.grails.datastore.gorm.neo4j.Neo4jMappingContext.<init>(Neo4jMappingContext.java:92)
	at org.grails.datastore.gorm.neo4j.Neo4jDatastore.createMappingContext(Neo4jDatastore.java:282)
	at org.grails.datastore.gorm.neo4j.Neo4jDatastore.<init>(Neo4jDatastore.java:216)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrConstructorNewInstance(ReflectiveInterceptor.java:1075)```

Here you can download a sample project where you can reproduce it just by starting it: https://github.com/mburak/neo4j-app

**Comment by graemerocher** [comment] 2016-06-17 09:04
This issue is caused by https://issues.apache.org/jira/browse/GROOVY-7866

**Comment by graemerocher** [comment] 2016-06-17 09:04
It only impacts Grails 2.x since Grails 3.x doesn't enable ExpandoMetaClass by default

**Comment by graemerocher** [comment] 2016-06-17 09:16
Fixed by https://github.com/grails/grails-data-mapping/commit/8759259efd4b2d4f34982bc3fca88bdc76e1de72

**Closed by graemerocher** 2016-06-17 09:16 UTC

**Comment by mburak** [comment] 2016-06-17 11:00
I don't know if it's related to this change but now I'm getting:

```Caused by: groovy.lang.MissingPropertyException: No such property: jsonValidator for class: org.grails.datastore.mapping.config.groovy.DefaultMappingConfigurationBuilder
	at com.brinqa.platform.view.View$__clinit__closure4.doCall(View.groovy:57)```

My constraint looks like this:

    static constraints = {
        manifest blank: false, validator: jsonValidator
    }

    private static jsonValidator = { String json, obj, errors ->
    ....
    }

This was working before this change.

**Comment by graemerocher** [comment] 2016-06-17 14:05
Right,due to the bug in Groovy (GROOVY-7866) so you would need to either to `Foo.jsonValidator` or we can revert the change and you can rename your `attributes` property.

**Comment by mburak** [comment] 2016-06-17 14:13
I moved to the jsonValidator content just to be inside the constraint and that works. I think I can live with that for now.
